<?php
require DIR_EXTENSION . 'sixmoments/catalog/language/en-gb/module/sixmoments.php';
$_['six_announcement'] = 'Бесплатная застрахованная доставка и возврат';
$_['six_catalog'] = 'Каталог'; $_['six_about'] = 'О нас'; $_['six_journal'] = 'Журнал'; $_['six_quiz'] = 'Найди свой момент'; $_['six_diamonds'] = 'Бриллианты'; $_['six_contact'] = 'Личная консультация'; $_['six_account'] = 'Аккаунт'; $_['six_wishlist'] = 'Избранное'; $_['six_bag'] = 'Корзина'; $_['six_menu'] = 'Меню'; $_['six_search'] = 'Поиск украшений';
$_['six_hero_kicker'] = 'Украшения для жизни, наполненной смыслом'; $_['six_hero_title'] = 'Где моменты становятся наследием.'; $_['six_hero_primary'] = 'Смотреть каталог'; $_['six_hero_secondary'] = 'Пройти квиз';
$_['six_signature'] = 'Знаковые украшения'; $_['six_desired'] = 'Самые желанные'; $_['six_desired_copy'] = 'Вневременные украшения, которые выбирают снова и снова'; $_['six_view_all'] = 'Смотреть все';
$_['six_collections'] = 'Коллекции'; $_['six_collections_title'] = 'Откройте вневременные украшения'; $_['six_collections_copy'] = 'Современные реликвии из золота и бриллиантов';
$_['six_moment_yes'] = 'Да'; $_['six_moment_forever'] = 'Навсегда'; $_['six_moment_new_life'] = 'Новая жизнь'; $_['six_moment_victory'] = 'Моя победа'; $_['six_moment_deserve'] = 'Я заслуживаю'; $_['six_moment_with_me'] = 'С собой';
$_['six_specials'] = 'Спецпредложения'; $_['six_specials_title'] = 'Выбрано для этого момента'; $_['six_lab_kicker'] = 'Лабораторные бриллианты'; $_['six_lab_title'] = 'То же сияние. Современное происхождение.'; $_['six_shop_lab'] = 'Смотреть лабораторные'; $_['six_discover_more'] = 'Узнать больше';
$_['six_story_kicker'] = 'Наша философия'; $_['six_story_title'] = 'Жизнь запоминается моментами.'; $_['six_read_story'] = 'Читать нашу историю'; $_['six_follow'] = 'Подписывайтесь на Instagram'; $_['six_follow_copy'] = 'Вневременное вдохновение и эксклюзивные новинки';
$_['six_newsletter_title'] = 'Присоединяйтесь к миру Six Moments'; $_['six_newsletter_copy'] = 'Первыми узнавайте о новых коллекциях, эксклюзивных релизах и закрытых предложениях'; $_['six_newsletter_placeholder'] = 'Ваш email'; $_['six_join'] = 'Присоединиться';
$_['six_footer_about'] = 'О нас'; $_['six_footer_care'] = 'Покупателям'; $_['six_footer_info'] = 'Информация'; $_['six_footer_account'] = 'Аккаунт'; $_['six_shipping'] = 'Доставка'; $_['six_returns'] = 'Возврат и обмен'; $_['six_faq'] = 'Вопросы и ответы'; $_['six_care'] = 'Уход за украшениями'; $_['six_size_guide'] = 'Размерная сетка';
$_['six_product_code'] = 'Артикул'; $_['six_weight'] = 'Вес'; $_['six_stock'] = 'Наличие'; $_['six_in_stock'] = 'В наличии'; $_['six_preorder'] = 'Под заказ'; $_['six_add_to_bag'] = 'Добавить в корзину';
$_['six_hint_title'] = 'Намекнуть на подарок'; $_['six_hint_copy'] = 'Отправьте близкому деликатную подсказку об этом украшении.'; $_['six_sender_name'] = 'Ваше имя'; $_['six_sender_email'] = 'Ваш email'; $_['six_recipient_name'] = 'Имя получателя'; $_['six_recipient_email'] = 'Email получателя'; $_['six_message'] = 'Личное сообщение'; $_['six_send_hint'] = 'Отправить намек'; $_['six_may_like'] = 'Может понравиться';
$_['six_description'] = 'Описание'; $_['six_details'] = 'Характеристики'; $_['six_delivery'] = 'Доставка и возврат'; $_['six_filters'] = 'Фильтры'; $_['six_sort'] = 'Сортировка'; $_['six_no_products'] = 'По этим фильтрам пока ничего не найдено.';
$_['six_quiz_title'] = 'Найди свой момент'; $_['six_quiz_intro'] = 'Четыре коротких вопроса — и персональная подборка для вашей истории.'; $_['six_start'] = 'Начать'; $_['six_next'] = 'Продолжить'; $_['six_back'] = 'Назад'; $_['six_result'] = 'Ваш момент'; $_['six_quiz_occasion'] = 'Что вы отмечаете?'; $_['six_quiz_budget'] = 'Какой бюджет комфортен?'; $_['six_quiz_type'] = 'Какое украшение вам ближе?'; $_['six_quiz_metal'] = 'Выберите металл'; $_['six_quiz_stone'] = 'Выберите происхождение камня';
$_['six_about_title'] = 'Жизнь запоминается моментами.'; $_['six_diamonds_title'] = 'Лабораторные и натуральные бриллианты'; $_['six_shipping_title'] = 'Доставка и оплата'; $_['six_faq_title'] = 'Частые вопросы'; $_['six_privacy_title'] = 'Политика конфиденциальности'; $_['six_terms_title'] = 'Условия использования'; $_['six_imprint_title'] = 'Юридическая информация'; $_['six_success_subscribe'] = 'Добро пожаловать в мир Six Moments.'; $_['six_success_hint'] = 'Деликатный намек отправлен.';
