<?php
require DIR_EXTENSION . 'sixmoments/catalog/language/en-gb/module/sixmoments.php';
$_['six_announcement'] = 'Безкоштовна застрахована доставка та повернення';
$_['six_catalog'] = 'Каталог'; $_['six_about'] = 'Про нас'; $_['six_journal'] = 'Журнал'; $_['six_quiz'] = 'Знайди свій момент'; $_['six_diamonds'] = 'Діаманти'; $_['six_contact'] = 'Приватна консультація'; $_['six_account'] = 'Акаунт'; $_['six_wishlist'] = 'Обране'; $_['six_bag'] = 'Кошик'; $_['six_menu'] = 'Меню'; $_['six_search'] = 'Пошук прикрас';
$_['six_hero_kicker'] = 'Прикраси для життя, сповненого сенсу'; $_['six_hero_title'] = 'Де моменти стають спадщиною.'; $_['six_hero_primary'] = 'Переглянути каталог'; $_['six_hero_secondary'] = 'Пройти квіз';
$_['six_signature'] = 'Знакові прикраси'; $_['six_desired'] = 'Найбажаніші'; $_['six_desired_copy'] = 'Позачасові прикраси, які обирають знову і знову'; $_['six_view_all'] = 'Переглянути всі';
$_['six_collections'] = 'Колекції'; $_['six_collections_title'] = 'Відкрийте позачасові прикраси'; $_['six_collections_copy'] = 'Сучасні реліквії із золота та діамантів';
$_['six_moment_yes'] = 'Так'; $_['six_moment_forever'] = 'Назавжди'; $_['six_moment_new_life'] = 'Нове життя'; $_['six_moment_victory'] = 'Моя перемога'; $_['six_moment_deserve'] = 'Я заслуговую'; $_['six_moment_with_me'] = 'Із собою';
$_['six_specials'] = 'Спецпропозиції'; $_['six_specials_title'] = 'Обрано для цього моменту'; $_['six_lab_kicker'] = 'Лабораторні діаманти'; $_['six_lab_title'] = 'Те саме сяйво. Сучасне походження.'; $_['six_shop_lab'] = 'Переглянути лабораторні'; $_['six_discover_more'] = 'Дізнатися більше';
$_['six_story_kicker'] = 'Наша філософія'; $_['six_story_title'] = 'Життя запам’ятовується моментами.'; $_['six_read_story'] = 'Читати нашу історію'; $_['six_follow'] = 'Підписуйтеся на Instagram'; $_['six_follow_copy'] = 'Позачасове натхнення та ексклюзивні новинки';
$_['six_newsletter_title'] = 'Приєднуйтеся до світу Six Moments'; $_['six_newsletter_copy'] = 'Першими дізнавайтеся про нові колекції, ексклюзивні релізи та приватні пропозиції'; $_['six_newsletter_placeholder'] = 'Ваш email'; $_['six_join'] = 'Приєднатися';
$_['six_footer_about'] = 'Про нас'; $_['six_footer_care'] = 'Покупцям'; $_['six_footer_info'] = 'Інформація'; $_['six_footer_account'] = 'Акаунт'; $_['six_shipping'] = 'Доставка'; $_['six_returns'] = 'Повернення та обмін'; $_['six_faq'] = 'Питання та відповіді'; $_['six_care'] = 'Догляд за прикрасами'; $_['six_size_guide'] = 'Розмірна сітка';
$_['six_product_code'] = 'Артикул'; $_['six_weight'] = 'Вага'; $_['six_stock'] = 'Наявність'; $_['six_in_stock'] = 'В наявності'; $_['six_preorder'] = 'Під замовлення'; $_['six_add_to_bag'] = 'Додати в кошик';
$_['six_hint_title'] = 'Натякнути на подарунок'; $_['six_hint_copy'] = 'Надішліть близькій людині делікатну підказку про цю прикрасу.'; $_['six_sender_name'] = 'Ваше ім’я'; $_['six_sender_email'] = 'Ваш email'; $_['six_recipient_name'] = 'Ім’я отримувача'; $_['six_recipient_email'] = 'Email отримувача'; $_['six_message'] = 'Особисте повідомлення'; $_['six_send_hint'] = 'Надіслати натяк'; $_['six_may_like'] = 'Може сподобатися';
$_['six_description'] = 'Опис'; $_['six_details'] = 'Характеристики'; $_['six_delivery'] = 'Доставка та повернення'; $_['six_filters'] = 'Фільтри'; $_['six_sort'] = 'Сортування'; $_['six_no_products'] = 'За цими фільтрами поки нічого не знайдено.';
$_['six_quiz_title'] = 'Знайди свій момент'; $_['six_quiz_intro'] = 'Чотири короткі запитання — і персональна добірка для вашої історії.'; $_['six_start'] = 'Почати'; $_['six_next'] = 'Продовжити'; $_['six_back'] = 'Назад'; $_['six_result'] = 'Ваш момент'; $_['six_quiz_occasion'] = 'Що ви святкуєте?'; $_['six_quiz_budget'] = 'Який бюджет комфортний?'; $_['six_quiz_type'] = 'Яка прикраса вам ближча?'; $_['six_quiz_metal'] = 'Оберіть метал'; $_['six_quiz_stone'] = 'Оберіть походження каменю';
$_['six_about_title'] = 'Життя запам’ятовується моментами.'; $_['six_diamonds_title'] = 'Лабораторні та натуральні діаманти'; $_['six_shipping_title'] = 'Доставка та оплата'; $_['six_faq_title'] = 'Часті запитання'; $_['six_privacy_title'] = 'Політика конфіденційності'; $_['six_terms_title'] = 'Умови використання'; $_['six_imprint_title'] = 'Юридична інформація'; $_['six_success_subscribe'] = 'Ласкаво просимо до світу Six Moments.'; $_['six_success_hint'] = 'Делікатний натяк надіслано.';
