<?php
namespace Opencart\Catalog\Controller\Extension\Sixmoments;
class Hint extends \Opencart\System\Engine\Controller {
    public function send(): void {
        $this->load->language('extension/sixmoments/module/sixmoments');$json=[];$required=['sender_name','sender_email','recipient_name','recipient_email'];foreach($required as $key){if(!trim((string)($this->request->post[$key]??'')))$json['error']='Please complete every required field.';}if(!filter_var($this->request->post['sender_email']??'',FILTER_VALIDATE_EMAIL)||!filter_var($this->request->post['recipient_email']??'',FILTER_VALIDATE_EMAIL))$json['error']=$this->language->get('six_error_email');
        if(!$json){$p=$this->request->post;$this->db->query("INSERT INTO `".DB_PREFIX."sixmoments_hint` SET `product_id`='".(int)($p['product_id']??0)."',`sender_name`='".$this->db->escape($p['sender_name'])."',`sender_email`='".$this->db->escape($p['sender_email'])."',`recipient_name`='".$this->db->escape($p['recipient_name'])."',`recipient_email`='".$this->db->escape($p['recipient_email'])."',`message`='".$this->db->escape((string)($p['message']??''))."',`language_code`='".$this->db->escape($this->config->get('config_language'))."',`date_added`=NOW()");$this->sendMail($p);$json['success']=$this->language->get('six_success_hint');}
        $this->response->addHeader('Content-Type: application/json');$this->response->setOutput(json_encode($json));
    }
    private function sendMail(array $p): void { if(!$this->config->get('config_mail_engine'))return;$o=['parameter'=>$this->config->get('config_mail_parameter'),'smtp_hostname'=>$this->config->get('config_mail_smtp_hostname'),'smtp_username'=>$this->config->get('config_mail_smtp_username'),'smtp_password'=>html_entity_decode($this->config->get('config_mail_smtp_password'),ENT_QUOTES,'UTF-8'),'smtp_port'=>$this->config->get('config_mail_smtp_port'),'smtp_timeout'=>$this->config->get('config_mail_smtp_timeout')];$mail=new \Opencart\System\Library\Mail($this->config->get('config_mail_engine'),$o);$mail->setTo($p['recipient_email']);$mail->setFrom($this->config->get('config_email'));$mail->setReplyTo($p['sender_email']);$mail->setSender('6MOMENTS');$mail->setSubject($p['sender_name'].' thought you might love this');$mail->setText($p['message']."\n\n".$this->url->link('product/product','product_id='.(int)$p['product_id'],true));$mail->send(); }
}
